src/main/java/com/gitlab/archetypeslabs/springjsf/managedbeans/seguridad/IdentidadBean.java
package com.gitlab.archetypeslabs.springjsf.managedbeans.seguridad;

import java.io.Serializable;

import org.springframework.security.authentication.UsernamePasswordAuthenticationToken;
import org.springframework.security.core.Authentication;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.stereotype.Component;
import org.springframework.web.context.annotation.RequestScope;

import com.gitlab.archetypeslabs.springjsf.entities.Persona;
import com.gitlab.archetypeslabs.springjsf.entities.Usuario;
import com.gitlab.archetypeslabs.springjsf.security.Identidad;

@Component("identidad")
@RequestScope
public class IdentidadBean implements Identidad, Serializable {

	@Override
	public boolean tienePermiso(String permiso) {
		UsernamePasswordAuthenticationToken token = getSecurityToken();
		return token != null && token.getAuthorities().stream()
				.anyMatch(grantedAuthority -> grantedAuthority.getAuthority().equals(permiso));
	}

	@Override
	public Long getIdPersona() {
		var persona = getPersona();
		return persona != null ? persona.getIdPersona() : null;
	}

	@Override
	public boolean isLoggedIn() {
		return getUsuarioDesdeSesion() != null;
	}

	@Override
	public String getNombrePersona() {
		var persona = getPersona();
		return persona != null ? persona.getNombres() : null;
	}

	@Override
	public Long getIdUsuario() {
		var usuario = getUsuarioDesdeSesion();
		return usuario != null ? usuario.getIdUsuario() : null;
	}

	@Override
	public String getEmail() {
		var usuario = getUsuarioDesdeSesion();
		return usuario != null ? usuario.getEmail() : null;
	}

	// privados

	private Persona getPersona() {
		var usuario = getUsuarioDesdeSesion();
		return usuario != null ? usuario.getPersona() : null;
	}

	private UsernamePasswordAuthenticationToken getSecurityToken() {
		Authentication authentication = SecurityContextHolder.getContext().getAuthentication();
		if (!(authentication instanceof UsernamePasswordAuthenticationToken)) {
			return null;
		}
		return (UsernamePasswordAuthenticationToken) authentication;
	}

	private Usuario getUsuarioDesdeSesion() {
		UsernamePasswordAuthenticationToken token = getSecurityToken();
		if (token != null && token.getPrincipal() != null && (token.getPrincipal() instanceof Usuario)) {
			return (Usuario) token.getPrincipal();
		}
		return null;
	}

}

src/main/webapp/WEB-INF/templates/footer.xhtml
<ui:composition 
    xmlns="http://www.w3.org/1999/xhtml"
    xmlns:f="http://xmlns.jcp.org/jsf/core"
    xmlns:h="http://xmlns.jcp.org/jsf/html"
    xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
    xmlns:p="http://primefaces.org/ui">
    
    <div class="footer">
    </div>
</ui:composition>

src/main/webapp/WEB-INF/templates/sidebar.xhtml
<ui:composition
        xmlns="http://www.w3.org/1999/xhtml"
        xmlns:f="http://xmlns.jcp.org/jsf/core"
        xmlns:h="http://xmlns.jcp.org/jsf/html"
        xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
        xmlns:p="http://primefaces.org/ui">

    <div class="sidebar">
        <h:form id="sidemenu-form">
            <div class="nano">
                <div class="nano-content sidebar-scroll-content">

                    <ui:fragment rendered="#{not identidad.loggedIn}">
                        <div class="profile">
                            <a href="#{request.contextPath}/login.xhtml">
                                <span>Iniciar Sesión</span>
                                <em class="fa fa-fw fa-sign-in"></em>
                            </a>
                        </div>
                    </ui:fragment>

                    <ui:fragment rendered="#{identidad.loggedIn}">
                        <div class="profile">
                            <p:graphicImage name="images/profile.png" library="omega-layout"/>
                            <a id="profile-button" href="#">
                                <span class="username">#{identidad.nombrePersona}</span>
                                <em class="fa fa-fw fa-cog"></em>
                            </a>
                            <ul>
                                <li><a href="#"><em class="fa fa-fw fa-sliders"></em><span>Cuenta</span></a></li>
                                <li><a href="#"><em class="fa fa-fw fa-bell"></em><span>Notificaciones</span><span
                                        class="menu-badge">2</span></a></li>
                                <li>
                                    <a href="#{request.contextPath}/logout">
                                        <em class="fa fa-fw fa-sign-out"></em><span>Cerrar Sesión</span>
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </ui:fragment>

                    <div class="menu">
                        <p:menubar>
                            <p:menuitem id="om_inicio" value="Inicio" icon="fa fa-home" url="/inicio.xhtml"/>
                            <p:menuitem id="om_gestionar_usuarios" value="Gestionar Usuarios" icon="fa fa-users"
                                        url="/ui/gestionar_usuarios"/>
                            <p:submenu id="om_components" label="Componentes" icon="fa fa-sitemap">
                                <p:menuitem id="om_dashboard" value="Dashboard" icon="fa fa-columns"
                                            url="/dashboard.xhtml"/>
                                <p:menuitem id="om_showcase_omega" value="Showcase Omega" icon="fa fa-code"
                                            url="/showcase_omega.xhtml"/>
                                <p:menuitem id="om_showcase_zeke" value="Showcase Zeke" icon="fa fa-code"
                                            url="/showcase_zeke.xhtml"/>
                            </p:submenu>
                            <p:submenu id="om_default" label="Template Pages" icon="fa fa-life-saver">
                                <p:menuitem id="om_empty" value="Empty Page" icon="fa fa-square-o" url="/empty.xhtml"/>
                                <p:menuitem id="om_login" value="Login Page" icon="fa fa-sign-in" url="/login.xhtml"/>
                                <p:menuitem id="om_error" value="Error Page" icon="fa fa-exclamation-circle"
                                            url="/error.xhtml"/>
                                <p:menuitem id="om_404" value="404 Page" icon="fa fa-times" url="/404.xhtml"/>
                                <p:menuitem id="om_access" value="Access Denied Page" icon="fa fa-exclamation-triangle"
                                            url="/access.xhtml"/>
                            </p:submenu>
                            <p:submenu id="om_hierarchy" label="Menu Hierarchy" icon="fa fa-gg">
                                <p:submenu id="om_sm1" label="Submenu 1" icon="fa fa-sign-in">
                                    <p:submenu id="om_sm11" label="Submenu 1.1" icon="fa fa-sign-in">
                                        <p:menuitem id="om_lnk111" value="Link 1.1.1" icon="fa fa-sign-in" url="#"/>
                                        <p:menuitem id="om_lnk112" value="Link 1.1.2" icon="fa fa-sign-in" url="#"/>
                                        <p:menuitem id="om_lnk113" value="Link 1.1.3" icon="fa fa-sign-in" url="#"/>
                                    </p:submenu>
                                    <p:submenu id="om_sm12" label="Submenu 1.2" icon="fa fa-sign-in">
                                        <p:menuitem id="om_lnk121" value="Link 1.2.1" icon="fa fa-sign-in" url="#"/>
                                    </p:submenu>
                                </p:submenu>
                                <p:submenu id="om_sm2" label="Submenu 2" icon="fa fa-sign-in">
                                    <p:submenu id="om_sm21" label="Submenu 2.1" icon="fa fa-sign-in">
                                        <p:menuitem id="om_lnk211" value="Link 2.1.1" icon="fa fa-sign-in" url="#"/>
                                        <p:menuitem id="om_lnk212" value="Link 2.1.2" icon="fa fa-sign-in" url="#"/>
                                    </p:submenu>
                                    <p:submenu id="om_sm22" label="Submenu 2.2" icon="fa fa-sign-in">
                                        <p:menuitem id="om_lnk221" value="Link 2.2.1" icon="fa fa-sign-in" url="#"/>
                                    </p:submenu>
                                </p:submenu>
                            </p:submenu>

                            <p:menuitem id="om_doc" value="Documentation" icon="fa fa-book"/>
                        </p:menubar>
                    </div>
                </div>
            </div>
        </h:form>
    </div>

</ui:composition>

src/main/webapp/WEB-INF/templates/template.xhtml
<!DOCTYPE html>
<html lang="es" xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:p="http://primefaces.org/ui">

<h:head>
	<meta charset="utf-8" />
	<meta http-equiv="X-UA-Compatible" content="IE=edge" />
	<meta http-equiv="Content-Language" content="en" />
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<title>Spring Boot Jsf - <ui:insert name="title" /></title>
	<meta name="viewport"
		content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no, shrink-to-fit=no" />
	<meta name="description"
		content="This is an example dashboard created using build-in elements and components." />
	<meta name="msapplication-tap-highlight" content="no" />
	<!--
	    =========================================================
	    * ArchitectUI HTML Theme Dashboard - v1.0.0
	    =========================================================
	    * Product Page: https://dashboardpack.com
	    * Copyright 2019 DashboardPack (https://dashboardpack.com)
	    * Licensed under MIT (https://github.com/DashboardPack/architectui-html-theme-free/blob/master/LICENSE)
	    =========================================================
	    * The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
	    -->
	<link href="#{request.contextPath}/resources/app/images/favicon.ico"
		type="image/x-icon" rel="shortcut icon" />
	<link href="#{request.contextPath}/resources/theme/main.css"
		rel="stylesheet" />
	<link href="#{request.contextPath}/resources/app/css/estilos.css"
		rel="stylesheet" />

	<h:outputScript name="js/primefaces.spanish.locale.js" library="app" />
	<h:outputScript name="js/jquery.Rut.js" library="app" />
	<h:outputScript name="js/csrf.js" library="app" />
	<h:outputScript name="js/viewExpired.js" library="app" />
	<h:outputScript name="js/general.js" library="app" />

</h:head>

<h:body>
	<div
		class="app-container app-theme-white body-tabs-shadow fixed-sidebar fixed-header">
		<div class="app-main" style="z-index: auto">
			<div class="app-sidebar sidebar-shadow bg-focus sidebar-text-light"
				style="z-index: auto">
				<div class="app-header__logo">
					<div class="logo-src"></div>
					<div class="header__pane ml-auto">
						<div>
							<button type="button"
								class="hamburger close-sidebar-btn hamburger--elastic"
								data-class="closed-sidebar">
								<span class="hamburger-box"> <span
									class="hamburger-inner"></span>
								</span>
							</button>
						</div>
					</div>
				</div>
				<div class="app-header__mobile-menu">
					<div>
						<button type="button"
							class="hamburger hamburger--elastic mobile-toggle-nav">
							<span class="hamburger-box"> <span class="hamburger-inner"></span>
							</span>
						</button>
					</div>
				</div>
				<div class="app-header__menu">
					<span>
						<button type="button"
							class="btn-icon btn-icon-only btn btn-primary btn-sm mobile-toggle-header-nav">
							<span class="btn-icon-wrapper"> <em
								class="fa fa-ellipsis-v fa-w-6"></em>
							</span>
						</button>
					</span>
				</div>
				<div class="scrollbar-sidebar">
					<div class="app-sidebar__inner">
						<ul class="vertical-nav-menu">
							<li class="app-sidebar__heading">Dashboards</li>
							<li><a href="#{request.contextPath}/dashboard2.xhtml"> <em
									class="metismenu-icon pe-7s-rocket"></em> Original Theme
							</a></li>
							<li><a href="#{request.contextPath}/showcase"> <em
									class="metismenu-icon pe-7s-graph2"></em> Showcase
							</a></li>
							<li class="app-sidebar__heading">Secciones</li>
							<li><a href="#"> <em
									class="metismenu-icon pe-7s-diamond"></em> Elements <em
									class="metismenu-state-icon pe-7s-angle-down caret-left"
									style="float: right; position: relative;"></em>
							</a>
								<ul>
									<li><a href="elements-buttons-standard.html"> <em
											class="metismenu-icon"></em> Buttons
									</a></li>
									<li><a href="elements-dropdowns.html"> <em
											class="metismenu-icon"> </em>Dropdowns
									</a></li>
									<li><a href="elements-icons.html"> <em
											class="metismenu-icon"> </em>Icons
									</a></li>
									<li><a href="elements-badges-labels.html"> <em
											class="metismenu-icon"> </em>Badges
									</a></li>
									<li><a href="elements-cards.html"> <em
											class="metismenu-icon"> </em>Cards
									</a></li>
									<li><a href="elements-list-group.html"> <em
											class="metismenu-icon"> </em>List Groups
									</a></li>
									<li><a href="elements-navigation.html"> <em
											class="metismenu-icon"> </em>Navigation Menus
									</a></li>
									<li><a href="elements-utilities.html"> <em
											class="metismenu-icon"> </em>Utilities
									</a></li>
								</ul></li>
							<li><a href="#"> <em class="metismenu-icon pe-7s-car"></em>
									Components <em
									class="metismenu-state-icon pe-7s-angle-down caret-left"
									style="float: right; position: relative;"></em>
							</a>
								<ul>
									<li><a href="components-tabs.html"> <em
											class="metismenu-icon"> </em>Tabs
									</a></li>
									<li><a href="components-accordions.html"> <em
											class="metismenu-icon"> </em>Accordions
									</a></li>
									<li><a href="components-notifications.html"> <em
											class="metismenu-icon"> </em>Notifications
									</a></li>
									<li><a href="components-modals.html"> <em
											class="metismenu-icon"> </em>Modals
									</a></li>
									<li><a href="components-progress-bar.html"> <em
											class="metismenu-icon"> </em>Progress Bar
									</a></li>
									<li><a href="components-tooltips-popovers.html"> <em
											class="metismenu-icon"> </em>Tooltips &amp; Popovers
									</a></li>
									<li><a href="components-carousel.html"> <em
											class="metismenu-icon"> </em>Carousel
									</a></li>
									<li><a href="components-calendar.html"> <em
											class="metismenu-icon"> </em>Calendar
									</a></li>
									<li><a href="components-pagination.html"> <em
											class="metismenu-icon"> </em>Pagination
									</a></li>
									<li><a href="components-scrollable-elements.html"> <em
											class="metismenu-icon"> </em>Scrollable
									</a></li>
									<li><a href="components-maps.html"> <em
											class="metismenu-icon"> </em>Maps
									</a></li>
								</ul></li>
							<li><a href="tables-regular.html"> <em
									class="metismenu-icon pe-7s-display2"></em> Tables
							</a></li>
						</ul>
					</div>
				</div>
			</div>
			<div class="app-header header-shadow bg-primary header-text-light"
				style="z-index: auto">
				<div class="app-header__logo">
					<div class="logo-src"></div>
					<div class="header__pane ml-auto">
						<div>
							<button type="button"
								class="hamburger close-sidebar-btn hamburger--elastic"
								data-class="closed-sidebar">
								<span class="hamburger-box"> <span
									class="hamburger-inner"></span>
								</span>
							</button>
						</div>
					</div>
				</div>
				<div class="app-header__mobile-menu">
					<div>
						<button type="button"
							class="hamburger hamburger--elastic mobile-toggle-nav">
							<span class="hamburger-box"> <span class="hamburger-inner"></span>
							</span>
						</button>
					</div>
				</div>
				<div class="app-header__menu">
					<span>
						<button type="button"
							class="btn-icon btn-icon-only btn btn-primary btn-sm mobile-toggle-header-nav">
							<span class="btn-icon-wrapper"> <em
								class="fa fa-ellipsis-v fa-w-6"></em>
							</span>
						</button>
					</span>
				</div>
				<div class="app-header__content">
					<div class="app-header-left">
						<ul class="header-menu nav">
							<li class="nav-item"><a href="javascript:void(0);"
								class="nav-link"> <em class="nav-link-icon fa fa-database">
								</em> Statistics
							</a></li>
							<li class="btn-group nav-item"><a href="javascript:void(0);"
								class="nav-link"> <em class="nav-link-icon fa fa-edit"></em>
									Projects
							</a></li>
							<li class="dropdown nav-item"><a href="javascript:void(0);"
								class="nav-link"> <em class="nav-link-icon fa fa-cog"></em>
									Settings
							</a></li>
						</ul>
					</div>
					<div class="app-header-right">
						<div class="header-btn-lg pr-0">
							<div class="widget-content p-0">
								<div class="widget-content-wrapper">
									<div class="widget-content-left">
										<div class="btn-group">
											<a data-toggle="dropdown" aria-haspopup="true"
												aria-expanded="false" class="p-0 btn"> <img width="42"
												class="rounded-circle"
												src="#{request.contextPath}/resources/theme/assets/images/avatars/1.jpg"
												alt="" /><em class="fa fa-angle-down ml-2 opacity-8"></em>
											</a>
											<div tabindex="-1" role="menu" aria-hidden="true"
												class="dropdown-menu dropdown-menu-right">
												<button type="button" tabindex="0" class="dropdown-item">User
													Account</button>
												<button type="button" tabindex="0" class="dropdown-item">Settings</button>
												<h6 tabindex="-1" class="dropdown-header">Header</h6>
												<button type="button" tabindex="0" class="dropdown-item">Actions</button>
												<div tabindex="-1" class="dropdown-divider"></div>
												<button type="button" tabindex="0" class="dropdown-item">Dividers</button>
											</div>
										</div>
									</div>
									<div class="widget-content-left  ml-3 header-user-info">
										<div class="widget-heading">Alina Mclourd</div>
										<div class="widget-subheading">VP People Manager</div>
									</div>
									<div class="widget-content-right header-user-info ml-3">
										<button type="button"
											class="btn-shadow p-1 btn btn-primary btn-sm show-toastr-example">
											<em class="fa text-white fa-calendar pr-1 pl-1"></em>
										</button>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
			<div class="app-main__outer" style="z-index: auto">
				<div class="app-main__inner">
					<ui:insert name="content" />
				</div>
				<div class="app-wrapper-footer">
					<div class="app-footer">
						<div class="app-footer__inner">
							<div class="app-footer-left">
								<ul class="nav">
									<li class="nav-item"><a href="javascript:void(0);"
										class="nav-link"> Footer Link 1 </a></li>
									<li class="nav-item"><a href="javascript:void(0);"
										class="nav-link"> Footer Link 2 </a></li>
								</ul>
							</div>
							<div class="app-footer-right">
								<ul class="nav">
									<li class="nav-item"><a href="javascript:void(0);"
										class="nav-link"> Footer Link 3 </a></li>
									<li class="nav-item"><a href="javascript:void(0);"
										class="nav-link">
											<div class="badge badge-success mr-1 ml-0">
												<small>NEW</small>
											</div> Footer Link 4
									</a></li>
								</ul>
							</div>
						</div>
					</div>
				</div>

			</div>
		</div>
	</div>

	<script type="text/javascript"
		src="#{request.contextPath}/resources/theme/assets/scripts/main.js"></script>

	<ui:include src="/WEB-INF/templates/includes/mensajes_globales.xhtml" />
	<ui:include src="/WEB-INF/templates/includes/idleMonitor.xhtml" />
	<ui:include
		src="/WEB-INF/templates/includes/funciones_javascript_globales.xhtml" />
	<ui:include src="/WEB-INF/templates/includes/csrf.xhtml" />
	<p:ajaxStatus onstart="PF('statusDialog').show()"
		oncomplete="PF('statusDialog').hide()" />

</h:body>
</html>

src/main/webapp/WEB-INF/templates/topbar.xhtml
<ui:composition 
    xmlns="http://www.w3.org/1999/xhtml"
    xmlns:f="http://xmlns.jcp.org/jsf/core"
    xmlns:h="http://xmlns.jcp.org/jsf/html"
    xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
    xmlns:p="http://primefaces.org/ui">

    <div class="topbar clearfix">
    
        <span class="topbar-title"><ui:insert name="title"></ui:insert></span>
        
    </div>
    
</ui:composition>